[versions]
# Android
sdk-min = "21"
sdk-compile = "33"
sdk-target = "33"

# Plugins
agp = "7.4.2"
detekt = "1.23.0"
dokka = "1.8.20"
kotlin = "1.8.22"
kover = "0.7.5"
ktlint-cli = "1.1.1"
ktlint-gradle = "11.6.1"
licensee = "1.7.0"
publish = "0.25.3"
spotless = "6.25.0"

# Libraries
alakazam = "4.3.1"
androidx-compose-bom = "2023.10.01"
androidx-compose-compiler = "1.4.8"
androidx-coreKtx = "1.2.0"
androidx-lifecycle = "2.6.0"
atak-sdk = "5.0.0.17"
dagger = "2.50"
flowpreferences = "1.9.1"
kotlinx-coroutines = "1.6.4"
kotlinx-datetime = "0.4.0"
kotlinx-immutable = "0.3.5"
timber = "5.0.1"

# Testing
androidx-arch-test = "2.2.0"
androidx-junit = "1.1.5"
androidx-rules = "1.5.0"
androidx-runner = "1.5.2"
androidx-test = "1.5.0"
junit = "4.13.2"
mockk = "1.13.7"
robolectric = "4.10.3"
turbine = "1.0.0"

[libraries]
# Plugins
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version.ref = "licensee" }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

# Libraries
alakazam-android-core = { module = "dev.jonpoulton.alakazam:android-core", version.ref = "alakazam" }
alakazam-android-compose = { module = "dev.jonpoulton.alakazam:android-ui-compose", version.ref = "alakazam" }
alakazam-kotlin-core = { module = "dev.jonpoulton.alakazam:kotlin-core", version.ref = "alakazam" }
alakazam-kotlin-time = { module = "dev.jonpoulton.alakazam:kotlin-time", version.ref = "alakazam" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material-core = { module = "androidx.compose.material:material" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-core = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
atak-sdk = { module = "com.atakmap.civ.common:api", version.ref = "atak-sdk" }
dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
flowpreferences = { module = "com.fredporciuncula:flow-preferences", version.ref = "flowpreferences" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Testing
test-alakazam-core = { module = "dev.jonpoulton.alakazam:testing-core", version.ref = "alakazam" }
test-androidx-arch = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-test" }
test-androidx-coreKtx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
test-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
test-androidx-rules = { module = "androidx.test:rules", version.ref = "androidx-rules" }
test-androidx-runner = { module = "androidx.test:runner", version.ref = "androidx-runner" }
test-junit = { module = "junit:junit", version.ref = "junit" }
test-kotlin-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
test-kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
test-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
test-mockk-core = { module = "io.mockk:mockk", version.ref = "mockk" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
agp = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
