name: Release

on:
  push:
    tags:
      - '**'

  workflow_dispatch:

env:
  CI: true

jobs:
  verify-version:
    runs-on: ubuntu-latest

    outputs:
      git-tag: ${{ steps.git-tag.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0 # get everything

      - name: Get Git tag
        id: git-tag
        run: |
          GIT_TAG=$(git describe --tags --abbrev=0)
          echo "GIT_TAG=$GIT_TAG"
          echo "version=$GIT_TAG" >> $GITHUB_OUTPUT

      - name: Get Gradle version
        id: gradle-version
        run: |
          GRADLE_VERSION=$(cat gradle.properties | grep VERSION_NAME | cut -d "=" -f 2)
          echo "GRADLE_VERSION=$GRADLE_VERSION"
          echo "version=$GRADLE_VERSION" >> $GITHUB_OUTPUT

      - name: Verify Git tag matches Gradle version
        run: |
          GRADLE_VERSION="${{ steps.gradle-version.outputs.version }}"
          GIT_TAG="${{ steps.git-tag.outputs.version }}"
          if [ -z "$GRADLE_VERSION" ]; then
            echo "Empty gradle version"
            exit 1
          elif [ -z "$GIT_TAG" ]; then
            echo "Empty git tag"
            exit 1
          elif [ "$GRADLE_VERSION" != "$GIT_TAG" ]; then
            echo "Gradle version = $GRADLE_VERSION, Git tag = $GIT_TAG => MISMATCH!"
            exit 1
          fi

  release:
    runs-on: ubuntu-latest
    needs: verify-version

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: v${{ needs.verify-version.outputs.git-tag }}
